'use strict';
const view = window.AgentEduView;
const $ = selector => document.querySelector(selector);
let activeKp = null;
let profiles = [], picked = null, S = null, IV = null, customBackground = null;
const TONE = {AUDIT:'pass', REVISE:'revise', GENERATE:'dispatch', DECIDE:'dispatch', DIAGNOSE:'dispatch', PLAN:'', ASSEMBLE:'pass', READY:'pass', FEEDBACK:''};

function esc(value){ return String(value == null ? '' : value).replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char])); }
function clean(value){ return view && view.cleanDisplayText ? view.cleanDisplayText(value) : String(value || ''); }
function reduceMotion(){ return matchMedia('(prefers-reduced-motion: reduce)').matches; }
function sourceWithLink(source){ return String(source || '').split(/(https?:\/\/[^\s<]+)/g).map(part => /^https?:\/\//.test(part) ? `<a class="source-link" href="${esc(part)}" target="_blank" rel="noopener noreferrer">打开原始来源</a>` : esc(part)).join(''); }
function showAlert(message){ const alert = $('#uiAlert'); alert.textContent = message; alert.hidden = false; }
function clearAlert(){ $('#uiAlert').hidden = true; }
function updateWorkflowProgress(stage){ const steps = [['intake','填写学习情况'],['interview','完成测评'],['learn','阅读学习方案'],['feedback','提交学习反馈']]; const current = Math.max(0, steps.findIndex(([key]) => key === stage)); $('#workflowProgress').innerHTML = steps.map(([key, label], index) => `<span class="workflow-step"${index === current ? ' aria-current="step"' : ''}>${index + 1}. ${label}</span>`).join(''); }
function revealLearningPlan(){ $('#learnerRecord').open = false; ['learningPlan','learningPath','learningContent','feedbackCard','evidencePanel'].forEach(id => { $('#'+id).hidden = false; }); updateWorkflowProgress('learn'); $('#learningPlan').scrollIntoView({block:'start', behavior:reduceMotion() ? 'auto' : 'smooth'}); }
async function api(path, body){ const options = body ? {method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)} : {}; const response = await fetch(path, options); const data = await response.json(); if(!response.ok) throw new Error(data.error || '请求失败'); return data; }

async function loadProfiles(){ try { profiles = await api('/api/profiles'); $('#pcount').textContent = profiles.length; $('#learners').innerHTML = profiles.map(profile => `<button class="learner" data-id="${esc(profile.id)}" aria-pressed="false"><div class="who">${esc(profile.name)}</div><div class="meta">${esc(profile.label)} · ${esc(profile.grade)} · 实操 ${esc(profile.hours)}h</div><div class="say">${esc(profile.self_report)}</div></button>`).join(''); document.querySelectorAll('.learner').forEach(button => button.onclick = () => { picked = button.dataset.id; document.querySelectorAll('.learner').forEach(item => item.setAttribute('aria-pressed', String(item === button))); $('#run').disabled = false; }); } catch(error) { showAlert('无法加载示例学习方案：' + error.message); } }
function intakeSummary(background, clarify){ const item = (name, value) => `<div><span>${name}</span><br>${esc(value || '未填写')}</div>`; const questions = clarify && clarify.length ? `<p>还可补充：${esc(clarify.join('；'))}</p>` : '<p>已了解你的学习情况，可以开始测评。</p>'; return `<b>已整理你的学习情况</b><div class="intake-fields">${item('学历/层次',background.education)}${item('年级/岗位',background.grade)}${item('专业方向',background.major)}${item('实操时长',(background.hands_on_hours || 0)+' 小时')}${item('学习目标',background.goal)}</div>${questions}`; }
async function parseIntake(){ const button = $('#parseIntake'); button.disabled = true; button.textContent = '正在整理…'; try { const result = await api('/api/intake',{text:$('#intakeText').value.trim()}); customBackground = result.background; $('#intakeSummary').innerHTML = intakeSummary(result.background,result.clarify); $('#intakeSummary').hidden = false; $('#startInterview').disabled = false; clearAlert(); } catch(error) { $('#intakeSummary').textContent = '无法解析：'+error.message; $('#intakeSummary').hidden = false; } button.disabled = false; button.textContent = '重新整理我的学习情况'; }
function renderInterview(result){ const snap = result.snapshot; $('#interviewCard').dataset.started = 'true'; switchEntryMode('custom'); updateWorkflowProgress('interview'); $('#interviewProgress').textContent = `${snap.asked} / ${snap.max_items}`; IV.item = result.item; if(!result.item){ $('#interviewQuestion').innerHTML = `<div class="notice ok"><b>你的测评已完成</b><br>已覆盖 ${snap.coverage} / ${snap.kp_total} 个知识点。</div>`; $('#finishInterview').hidden = false; return; } const item = result.item; $('#interviewQuestion').innerHTML = `<div class="interview-meta">第 ${snap.asked + 1} 题 · ${esc(item._kp_name || item.kp || '知识点')} · 难度 ${esc(item.level || '-')} · 来源 ${esc(item.source_id || '未标注')}</div><div class="interview-question">${esc(item.stem)}</div><div class="interview-options">${(item.options || []).map((option,index) => `<button class="answer interview-option" data-choice="${index}"><b>${String.fromCharCode(65+index)}.</b> ${esc(option)}</button>`).join('')}</div>`; document.querySelectorAll('.interview-option').forEach(button => button.onclick = () => answerInterview(Number(button.dataset.choice))); }
async function startInterview(){ if(!customBackground) return; const button = $('#startInterview'); button.disabled = true; button.textContent = '正在准备题目…'; setState('正在测评',true); try { const result = await api('/api/interview/start',{background:customBackground,max_items:12}); IV = {id:result.interview_id,background:customBackground,item:result.item}; renderInterview(result); } catch(error) { showAlert('无法开始测评：'+error.message); setState('故障',false); } button.disabled = false; button.textContent = '重新开始我的 12 题测评'; }
async function answerInterview(choice){ if(!IV || !IV.item) return; document.querySelectorAll('.interview-option').forEach(button => button.disabled = true); try { renderInterview(await api('/api/interview/answer',{interview_id:IV.id,item_id:IV.item.id,choice})); } catch(error) { showAlert('提交失败：'+error.message); document.querySelectorAll('.interview-option').forEach(button => button.disabled = false); } }
async function finishInterview(){ if(!IV) return; const button = $('#finishInterview'); button.disabled = true; button.textContent = '正在生成我的方案…'; setState('正在生成方案',false); $('#timeline').innerHTML = ''; try { S = await api('/api/interview/finish',{interview_id:IV.id,background:IV.background,max_kp:3}); render(); revealLearningPlan(); await stream(S.events,0); $('#interviewQuestion').innerHTML = '<div class="notice ok">已根据你的学习情况与实际作答，生成学习建议、学习路径和资料。</div>'; setState('准备就绪',true); } catch(error) { showAlert('生成失败：'+error.message); setState('故障',false); } button.disabled = false; button.textContent = '用测评结果生成我的方案'; }

function readFileBase64(file){ return new Promise((resolve,reject) => { const reader = new FileReader(); reader.onerror = () => reject(new Error('浏览器无法读取该文件')); reader.onload = () => resolve(String(reader.result).split(',',2)[1] || ''); reader.readAsDataURL(file); }); }
function bytesLabel(bytes){ return bytes < 1024*1024 ? `${Math.ceil(bytes/1024)} KiB` : `${(bytes/1024/1024).toFixed(2)} MiB`; }
async function stageMaterial(){ const file = $('#materialFile').files[0], result = $('#stageResult'); if(!file){ result.textContent = '请先选择要提交的资料。'; result.hidden = false; return; } const button = $('#stageMaterial'); button.disabled = true; button.textContent = '正在检查资料信息…'; try { const response = await api('/api/materials/stage',{filename:file.name,content_base64:await readFileBase64(file),source_description:$('#materialSource').value,rights_confirmed:$('#materialRights').checked}); const skipped = response.skipped.length ? `<br>未读取：${response.skipped.map(item => `${esc(item.file)}（${esc(item.reason)}）`).join('；')}` : ''; result.classList.add('ok'); result.innerHTML = `<b>资料已提交，暂未进入知识库。</b><br>${esc(response.filename)} · ${bytesLabel(response.bytes)}；可供复核的内容 ${response.sourced} 条，需要单独处理 ${response.quarantined} 条，待归类 ${response.unassigned} 条。${skipped}<br><span>接下来：${response.next_steps.map(esc).join('；')}</span>`; result.hidden = false; } catch(error) { result.classList.remove('ok'); result.textContent = '未暂存：'+error.message; result.hidden = false; } button.disabled = false; button.textContent = '提交并检查资料信息'; }

async function run(){ const button = $('#run'); button.disabled = true; button.textContent = '正在生成学习方案…'; setState('正在生成方案',false); $('#timeline').innerHTML = ''; try { S = await api('/api/run',{profile_id:picked,max_kp:3}); render(); revealLearningPlan(); await stream(S.events,0); setState('准备就绪',true); } catch(error) { showAlert('运行失败：'+error.message); $('#timeline').innerHTML = `<p class="empty">运行失败：${esc(error.message)}</p>`; setState('故障',false); } button.disabled = false; button.textContent = '重新查看这份学习方案'; }
function setState(text,on){ $('#stateTxt').textContent = text; $('#lamp').classList.toggle('on',!!on); }
async function stream(events,from){ const box = $('#timeline'); for(let index=from;index<events.length;index++){ box.insertAdjacentHTML('beforeend',stepHTML(events[index])); $('#ecount').textContent = `${index+1} 步`; if(!reduceMotion()) await new Promise(resolve => setTimeout(resolve,90)); } }
function stepHTML(event){ const dropped = event.detail && event.detail.dropped || []; const extra = dropped.length ? dropped.map(item => `<div class="claim">${esc(item.text)}<div class="src">拦截 · ${esc(item.note || '')}</div></div>`).join('') : ''; return `<div class="step" data-tone="${dropped.length ? 'block' : TONE[event.state] || ''}"><div class="seq">${esc(event.seq)}</div><div><div><span class="tagstate">${esc(event.state)}</span>${esc(event.agent)}</div><div>${esc(event.summary)}</div><div class="ms">${esc(event.ms)} ms</div>${extra}</div></div>`; }
function inlineResourceText(text){ return esc(clean(text)).replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>'); }
function resourceBody(resource){ if(resource.kind === 'quiz'){ const items = resource.items || []; return items.length ? `<ol>${items.map((item,index) => `<li>第 ${index+1} 题 · ${esc(item.stem)}<details><summary>查看答案与解析</summary><p>答案：${item.answer === false ? '错误' : '正确'}。${esc(item.explain || '')}</p></details></li>`).join('')}</ol>` : '<p class="empty">本资源暂未生成测试题。</p>'; } return clean(resource.body || '').split('\n').filter(Boolean).map(line => `<p>${inlineResourceText(line)}</p>`).join('') || '<p class="empty">本资源暂未生成正文。</p>'; }
function resourceCard(resource){ const labels = {both:'双方印证',single:'单方提出',arbitrated:'仲裁采纳'}; return `<article class="res"><div class="top"><span class="kind">${esc(resource.kind)}</span><span class="diff">难度 ${esc(resource.difficulty)}/5 · 断言 ${resource.claims.length}</span></div><div class="ttl">${esc(resource.title)}</div><details class="resource-body" open><summary>完整资源正文</summary><div class="resource-content">${resourceBody(resource)}</div></details><details><summary>核验与溯源</summary>${resource.claims.map(claim => { const kb = (S.kb || {})[claim.source_id] || {}; return `<div class="claim">${esc(claim.text)}<div class="src">${esc(claim.source_id || '无引用')} · ${sourceWithLink(kb.source)}</div><div class="src">${kb.verified ? '已人工核实' : '待核实'} · 证据 ${esc(claim.evidence_score)} · ${esc(labels[claim.consensus] || '未标注共识')}</div>${kb.source_note ? `<div>${esc(kb.source_note)}</div>` : ''}</div>`; }).join('')}</details></article>`; }
function renderLearningPath(){ $('#learningPath').innerHTML = `<h2><span class="section-number">03</span>建议学习顺序</h2><ol class="path-list">${S.path.map((kp,index) => `<li data-kp="${esc(kp)}">${esc(S.path_names[index])}</li>`).join('')}</ol>`; }
function render(){ const diagnosis = S.diagnosis; $('#dOverall').textContent = `${(diagnosis.overall*100).toFixed(1)}%`; $('#dEntry').textContent = `${diagnosis.entry_level} / 5`; $('#dGaps').textContent = `${diagnosis.gaps.length} 个`; $('#dNarr').textContent = clean(diagnosis.narrative); $('#rcount').textContent = S.resources.length; $('#resources').innerHTML = S.resources.map(resourceCard).join('') || '<p class="empty">暂未准备好学习资料。</p>'; renderLearningPath(); $('#fbKp').innerHTML = S.path.map((kp,index) => `<option value="${esc(kp)}">${esc(S.path_names[index])}</option>`).join(''); $('#fbKp').onchange = buildQuiz; activeKp = $('#fbKp').value; buildQuiz(); $('#charts').hidden = false; drawGaps(); drawFit(); drawPath(); }
function buildQuiz(){ activeKp = $('#fbKp').value; const resource = (view && view.resourcesForKp ? view.resourcesForKp(S.resources,activeKp) : S.resources.filter(item => item.kp === activeKp)).find(item => item.kind === 'quiz'); const items = resource && resource.items ? resource.items.slice(0,4) : []; if(!items.length){ $('#quiz').innerHTML = '<p class="empty">该知识点暂未生成可用于反馈的测试题。</p>'; $('#submitFb').disabled = true; return; } $('#submitFb').disabled = false; $('#quiz').innerHTML = items.map((item,index) => `<div class="feedback-question" data-answer="${item.answer === false ? '0' : '1'}"><div class="feedback-meta">第 ${index+1} 题 · 判断题 · 难度 ${esc(item.difficulty || '-')} · ${esc(item.source_id || '无引用')}</div><div>${esc(item.stem)}</div><button class="answer" data-value="1">正确</button><button class="answer" data-value="0">错误</button><div class="feedback-explain" hidden>${esc(item.explain || '')}</div></div>`).join(''); document.querySelectorAll('.answer').forEach(button => button.onclick = () => { const box = button.closest('.feedback-question'); box.querySelectorAll('.answer').forEach(item => item.removeAttribute('data-on')); button.dataset.on = '1'; box.dataset.pick = button.dataset.value; box.querySelector('.feedback-explain').hidden = false; }); }
async function submitFb(){ const boxes = [...document.querySelectorAll('.feedback-question')]; if(boxes.some(box => box.dataset.pick === undefined)){ $('#verdict').hidden = false; $('#verdict').textContent = '还有题目未作答，请为每道题选择“正确”或“错误”。'; return; } const button = $('#submitFb'); button.disabled = true; try { const before = S.events.length; S = await api('/api/feedback',{session_id:S.session_id,kp:activeKp,answers:boxes.map(box => box.dataset.pick === box.dataset.answer)}); $('#verdict').hidden = false; $('#verdict').innerHTML = `<b>${esc(S.decision.action)}</b> · ${esc(S.decision.reason)}`; const panel = $('#decisionPanel'); panel.hidden = false; panel.innerHTML = `<span class="section-number">06</span><b>下一步建议：</b> ${esc((view && view.feedbackNextAction ? view.feedbackNextAction(S.path,activeKp,S.decision).label : S.decision.action))}`; panel.focus(); updateWorkflowProgress('feedback'); await stream(S.events,before); render0(); } catch(error) { showAlert('提交反馈失败：'+error.message); } button.disabled = false; }
function render0(){ $('#resources').innerHTML = S.resources.map(resourceCard).join(''); renderLearningPath(); buildQuiz(); drawFit(); drawPath(); }
function svgEl(tag,attrs,text){ const element = document.createElementNS('http://www.w3.org/2000/svg',tag); Object.entries(attrs).forEach(([key,value]) => element.setAttribute(key,value)); if(text != null) element.textContent = text; return element; }
function drawGaps(){ const svg = $('#chartGaps'); svg.innerHTML = ''; S.diagnosis.mastery.slice().sort((a,b) => a.score-b.score).slice(0,12).forEach((mastery,index) => { const y = 12+index*23, width = 250*mastery.score; svg.append(svgEl('text',{x:124,y:y+14,'text-anchor':'end',class:'klabel'},mastery.name),svgEl('rect',{x:132,y,width:250,height:20,fill:'#eee9df'}),svgEl('rect',{x:132,y,width:Math.max(2,width),height:20,fill:S.diagnosis.gaps.includes(mastery.kp)?'var(--danger)':'var(--success)'})); }); }
function drawFit(){ const svg = $('#chartFit'); svg.innerHTML = ''; const kps = [...new Set(S.resources.map(resource => resource.kp))]; kps.forEach((kp,index) => { const x = 42+index*100; svg.append(svgEl('line',{x1:x,y1:30,x2:x,y2:245,stroke:'var(--line)'}),svgEl('text',{x,y:270,'text-anchor':'middle',class:'axis'},(S.kp_index[kp] || {}).name || kp)); S.resources.filter(resource => resource.kp === kp).forEach(resource => svg.appendChild(svgEl('circle',{cx:x,cy:245-(resource.difficulty-1)*48,r:6,fill:'var(--technical)'}))); }); }
function drawPath(){ const svg = $('#chartPath'); svg.innerHTML = ''; S.path.forEach((kp,index) => { const y = 20+index*55, name = S.path_names[index]; svg.append(svgEl('rect',{x:20,y,width:380,height:32,fill:'#f4f1e9',stroke:'var(--technical)'}),svgEl('text',{x:32,y:y+21,class:'klabel'},`${index+1}. ${name}`)); }); }
function switchEntryMode(mode){ document.querySelectorAll('[data-entry-panel]').forEach(panel => { const interview = panel.dataset.entryInterview === 'true'; panel.hidden = panel.dataset.entryPanel !== mode || (interview && panel.dataset.started !== 'true'); }); document.querySelectorAll('[data-entry-mode]').forEach(button => button.setAttribute('aria-selected',String(button.dataset.entryMode === mode))); }
function bindEntryMode(){ document.querySelectorAll('[data-entry-mode]').forEach(button => button.onclick = () => switchEntryMode(button.dataset.entryMode)); switchEntryMode('custom'); $('#intakeText').addEventListener('input',() => { customBackground = null; $('#startInterview').disabled = true; $('#intakeSummary').hidden = true; }); }
function bindActions(){ $('#run').onclick = run; $('#submitFb').onclick = submitFb; $('#parseIntake').onclick = parseIntake; $('#startInterview').onclick = startInterview; $('#finishInterview').onclick = finishInterview; $('#stageMaterial').onclick = stageMaterial; }
function boot(){ bindEntryMode(); bindActions(); updateWorkflowProgress('intake'); loadProfiles(); }
boot();
